import React from 'react';

const HistoryTab: React.FC = () => {
  return (
    <div className="tab-content">
      <div className="content-header">
        <svg className="content-icon" viewBox="0 0 24 24" fill="currentColor">
          <path d="M13.5,8H12V13L16.28,15.54L17,14.33L13.5,12.25V8M13,3A9,9 0 0,0 4,12H1L4.96,16.03L9,12H6A7,7 0 0,1 13,5A7,7 0 0,1 20,12A7,7 0 0,1 13,19C11.07,19 9.32,18.21 8.06,16.94L6.64,18.36C8.27,20 10.5,21 13,21A9,9 0 0,0 22,12A9,9 0 0,0 13,3"/>
        </svg>
        <h1 className="content-title">History</h1>
      </div>
      
      <div className="history-content">
        <div className="history-filters">
          <div className="filter-row">
            <div className="form-group">
              <label htmlFor="date-from">From Date</label>
              <input type="date" id="date-from" className="form-control" />
            </div>
            
            <div className="form-group">
              <label htmlFor="date-to">To Date</label>
              <input type="date" id="date-to" className="form-control" />
            </div>
            
            <div className="form-group">
              <label htmlFor="activity-type">Activity Type</label>
              <select id="activity-type" className="form-control">
                <option value="">All Activities</option>
                <option value="inquiry">Inquiry Created</option>
                <option value="updated">Information Updated</option>
                <option value="contract">Contract Signed</option>
                <option value="quotation">Quotation Generated</option>
                <option value="invoice">Invoice Created</option>
                <option value="payment">Payment Received</option>
              </select>
            </div>
            
            <button type="button" className="btn btn-primary filter-btn">Filter</button>
          </div>
        </div>
        
        <div className="history-timeline">
          <div className="timeline-item">
            <div className="timeline-marker"></div>
            <div className="timeline-content">
              <div className="timeline-header">
                <h4>Inquiry Created</h4>
                <span className="timestamp">2024-01-15 10:30 AM</span>
              </div>
              <p>Initial inquiry submitted for consulting services. Priority: High</p>
              <div className="timeline-meta">
                <span className="user">Created by: John Doe</span>
                <span className="status status-success">Completed</span>
              </div>
            </div>
          </div>
          
          <div className="timeline-item">
            <div className="timeline-marker"></div>
            <div className="timeline-content">
              <div className="timeline-header">
                <h4>Basic Information Updated</h4>
                <span className="timestamp">2024-01-15 2:45 PM</span>
              </div>
              <p>Company information and contact details updated</p>
              <div className="timeline-meta">
                <span className="user">Updated by: Jane Smith</span>
                <span className="status status-info">Info Updated</span>
              </div>
            </div>
          </div>
          
          <div className="timeline-item">
            <div className="timeline-marker"></div>
            <div className="timeline-content">
              <div className="timeline-header">
                <h4>Quotation Generated</h4>
                <span className="timestamp">2024-01-16 9:15 AM</span>
              </div>
              <p>Custom quotation generated based on requirements. Total: $45,000</p>
              <div className="timeline-meta">
                <span className="user">Generated by: System</span>
                <span className="status status-warning">Pending Review</span>
              </div>
            </div>
          </div>
          
          <div className="timeline-item">
            <div className="timeline-marker"></div>
            <div className="timeline-content">
              <div className="timeline-header">
                <h4>Contract Signed</h4>
                <span className="timestamp">2024-01-18 3:20 PM</span>
              </div>
              <p>Service agreement digitally signed by both parties</p>
              <div className="timeline-meta">
                <span className="user">Signed by: John Doe, Admin User</span>
                <span className="status status-success">Approved</span>
              </div>
            </div>
          </div>
          
          <div className="timeline-item">
            <div className="timeline-marker"></div>
            <div className="timeline-content">
              <div className="timeline-header">
                <h4>Invoice Created</h4>
                <span className="timestamp">2024-01-20 11:00 AM</span>
              </div>
              <p>Invoice #INV-2024-001 created for $45,000. Due date: 2024-02-19</p>
              <div className="timeline-meta">
                <span className="user">Created by: System</span>
                <span className="status status-warning">Pending Payment</span>
              </div>
            </div>
          </div>
        </div>
        
        <div className="history-stats">
          <div className="stat-card">
            <h3>Total Activities</h3>
            <span className="stat-number">15</span>
          </div>
          
          <div className="stat-card">
            <h3>Last Updated</h3>
            <span className="stat-number">2 hours ago</span>
          </div>
          
          <div className="stat-card">
            <h3>Status</h3>
            <span className="stat-number status-active">Active</span>
          </div>
        </div>
        
        <div className="form-actions">
          <button type="button" className="btn btn-outline-primary">Export History</button>
          <button type="button" className="btn btn-primary">Generate Report</button>
        </div>
      </div>
    </div>
  );
};

export default HistoryTab; 